[variables]
NODE_VERSION = "20"
NODE_OPTIONS = "--max_old_space_size=2048"
GENERATE_SOURCEMAP = "false"

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
